sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script:
  - yarn lint
  - yarn test
#deploy:
#  provider: script
#  skip_cleanup: true
#  before_deploy:
#    - git remote rm origin
#    - git remote add origin https://${GIT_USER}:${RELEASE_IT_GH_TOKEN}@github.com/${GIT_USER}/${PROJECT_NAME}.git
#    - git symbolic-ref HEAD refs/heads/develop
#    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
#    - yarn
#  script: yarn travis:release minor --preRelease=next
#  on:
#    branch: develop

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: develop
