sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install: yarn
script:
  - yarn lint
  - yarn test
deploy:
  provider: script
  before_deploy:
    - git remote rm origin
    - git remote add origin https://${GIT_USER}:${RELEASE_IT_GH_TOKEN}@github.com/${GIT_USER}/${PROJECT_NAME}.git
    - git symbolic-ref HEAD refs/heads/master
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
  script: yarn travis:publish:npm -- minor --preRelease=next
  on:
    branch: develop
