sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - /.*/
stages:
  - lint
  - test
  - release
install: yarn
jobs:
  include:
    - stage: lint
      name: Lint Project Sources
      script: yarn lint
    - stage: test
      name: Test Project Sources
      script: yarn test
    - stage: release
      name: Release Stable Version
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - yarn release:ci -- major
      on:
        branch: master
    -
      name: Release Pre-release Version
      script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - yarn release:ci -- minor --preRelease=next
      on:
        branch: develop
